### All user ratings

In [13]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

ratings = pd.read_csv('/home/gh23935521@sps.cuny.edu/Downloads/ratings.csv')
ratings

     rater         movie  rating
0     Noah        Friday     3.5
1     Noah       Hackers     3.0
2     Noah  Training Day     4.0
3     Noah       Aladdin     3.5
4     Noah    Madagascar     3.0
5     Noah       Sinners     4.5
6    Nicol        Friday     4.0
7    Nicol       Hackers     NaN
8    Nicol  Training Day     NaN
9    Nicol       Aladdin     4.5
10   Nicol    Madagascar     3.5
11   Nicol       Sinners     4.0
12    Lucy        Friday     4.5
13    Lucy       Hackers     NaN
14    Lucy  Training Day     4.0
15    Lucy       Aladdin     5.0
16    Lucy    Madagascar     3.0
17    Lucy       Sinners     5.0
18   Maria        Friday     2.0
19   Maria       Hackers     3.0
20   Maria  Training Day     5.0
21   Maria       Aladdin     3.5
22   Maria    Madagascar     NaN
23   Maria       Sinners     5.0
24  Gerald        Friday     5.0
25  Gerald       Hackers     3.5
26  Gerald  Training Day     3.5
27  Gerald       Aladdin     4.0
28  Gerald    Madagascar     4.0
29  Gerald       Sinners     NaN

### Average ratings for each movie

In [14]:
ratings.groupby('movie').rating.mean()

movie
Aladdin         4.100000
Friday          3.800000
Hackers         3.166667
Madagascar      3.375000
Sinners         4.625000
Training Day    4.125000
Name: rating, dtype: float64

### Average ratings for each rater

In [15]:
ratings.groupby('rater').rating.mean()

rater
Gerald    4.000000
Lucy      4.300000
Maria     3.700000
Nicol     4.000000
Noah      3.583333
Name: rating, dtype: float64

### All normalized rater ratings

In [16]:
# copies the data 
norm_ratings = ratings.copy() 
  
# apply normalization formula  
norm_ratings['rating'] = (norm_ratings['rating'] - norm_ratings['rating'].min()) / (norm_ratings['rating'].max() - norm_ratings['rating'].min())
      
# view normalized data 
norm_ratings

     rater         movie    rating
0     Noah        Friday  0.500000
1     Noah       Hackers  0.333333
2     Noah  Training Day  0.666667
3     Noah       Aladdin  0.500000
4     Noah    Madagascar  0.333333
5     Noah       Sinners  0.833333
6    Nicol        Friday  0.666667
7    Nicol       Hackers       NaN
8    Nicol  Training Day       NaN
9    Nicol       Aladdin  0.833333
10   Nicol    Madagascar  0.500000
11   Nicol       Sinners  0.666667
12    Lucy        Friday  0.833333
13    Lucy       Hackers       NaN
14    Lucy  Training Day  0.666667
15    Lucy       Aladdin  1.000000
16    Lucy    Madagascar  0.333333
17    Lucy       Sinners  1.000000
18   Maria        Friday  0.000000
19   Maria       Hackers  0.333333
20   Maria  Training Day  1.000000
21   Maria       Aladdin  0.500000
22   Maria    Madagascar       NaN
23   Maria       Sinners  1.000000
24  Gerald        Friday  1.000000
25  Gerald       Hackers  0.500000
26  Gerald  Training Day  0.500000
27  Gerald       Aladdin  0.666667
28  Gerald    Madagascar  0.666667
29  Gerald       Sinners       NaN

### Normalized movie averages

In [17]:
norm_ratings.groupby('movie').rating.mean()

movie
Aladdin         0.700000
Friday          0.600000
Hackers         0.388889
Madagascar      0.458333
Sinners         0.875000
Training Day    0.708333
Name: rating, dtype: float64

### Normalized rater averages

In [18]:
norm_ratings.groupby('rater').rating.mean()

rater
Gerald    0.666667
Lucy      0.766667
Maria     0.566667
Nicol     0.666667
Noah      0.527778
Name: rating, dtype: float64

### Conclusion

Using normalized data has the advantage of placing measurements of different units and scale along the same scale for more accurate comparisons. However, it has the disadvantage of scaling the data to a smaller interval when outliers are present, therefore hindering it's accuracy. For example, when the compared to the original user averages, all the normal averages are more varied when compared to the original averages, where you can see that all the movies are well favored amongst the raters, as all of those averages are closer to 5.

### [Extra Credit] All standardized rater ratings

In [19]:
std_ratings = ratings.copy()

# apply standardization formula  
std_ratings['rating'] = (std_ratings['rating'] - std_ratings['rating'].mean()) / (std_ratings['rating'].std())

std_ratings

     rater         movie    rating
0     Noah        Friday -0.505964
1     Noah       Hackers -1.138420
2     Noah  Training Day  0.126491
3     Noah       Aladdin -0.505964
4     Noah    Madagascar -1.138420
5     Noah       Sinners  0.758947
6    Nicol        Friday  0.126491
7    Nicol       Hackers       NaN
8    Nicol  Training Day       NaN
9    Nicol       Aladdin  0.758947
10   Nicol    Madagascar -0.505964
11   Nicol       Sinners  0.126491
12    Lucy        Friday  0.758947
13    Lucy       Hackers       NaN
14    Lucy  Training Day  0.126491
15    Lucy       Aladdin  1.391402
16    Lucy    Madagascar -1.138420
17    Lucy       Sinners  1.391402
18   Maria        Friday -2.403331
19   Maria       Hackers -1.138420
20   Maria  Training Day  1.391402
21   Maria       Aladdin -0.505964
22   Maria    Madagascar       NaN
23   Maria       Sinners  1.391402
24  Gerald        Friday  1.391402
25  Gerald       Hackers -0.505964
26  Gerald  Training Day -0.505964
27  Gerald       Aladdin  0.126491
28  Gerald    Madagascar  0.126491
29  Gerald       Sinners       NaN

### Standardized movie averages

In [20]:
std_ratings.groupby('movie').rating.mean()

movie
Aladdin         0.252982
Friday         -0.126491
Hackers        -0.927601
Madagascar     -0.664078
Sinners         0.917061
Training Day    0.284605
Name: rating, dtype: float64

### Standardized User Averages

In [21]:
std_ratings.groupby('rater').rating.mean()

rater
Gerald    0.126491
Lucy      0.505964
Maria    -0.252982
Nicol     0.126491
Noah     -0.400555
Name: rating, dtype: float64